### ISSUE TITLE
.class and .extension extensions for top level of .package directory

### ISSUE THREAD

**Issue by dalehenrich** [CampSmalltalk/Cypress#1]
Quick, take a look at the [STIG package](https://github.com/CampSmalltalk/STIG/tree/master/packages/STIG.package) and tell me which one of the classes listed there are in the package and which ones just contain extension methods....

For the current FileTree I use a classes and extensions directory to contain the extension classes [FileTree package](filetree / repository / MonticelloFileTree-Core.pkg / snapshot / extensions), but I think that using two directory extenstions:
- classes
- extensions{?)

eliminates the extra directory depth and provides the necessary distinction.

As Cypress stands you have to dip into the .class directory and check for a properties.json file...

**Comment by mkobetic** [comment]
I'm fine with this change. i'll steer STIG in that direction

**Comment by dalehenrich** [comment]
Cool ...

**Comment by mkobetic** [comment]
I ran into another issue with extensions. When I'm reading an extension method, I don't have a class name/namespace because the class directory doesn't include a properties.json in this case. I could deduce it from the directory name, but we said that may not be reliable. So the only other options I see is a) include a trimmed down properties.json in the class directory, presumably would just have a name and namespace keys, or b) include class name and namespace in the method .json file. What seems more reasonable ? Any other suggestions ?

**Comment by dalehenrich** [comment]
Offhand I think including it in the .json file makes the most sense ... no extra files floating around and we've got the .json for each method anyway ... for completeness we should include the class/namespace  in every method .json file ... 

Hmm, then every .json file would be platform dependent ... better to put a trimmed down properties.json in the class directory...

**Comment by mkobetic** [comment]
I was also torn between the two options. The method property version would actually be easier to implement in STIG, but I'm leaning towards the class level properties.json to avoid the (rather extensive) redundancy of information in the method properties. Especially if they'll have the tendency to stick out in the merges, the fewer there will be the better. So I'll go with the xxx.extension/properties.json option.

**Comment by mkobetic** [comment]
OK, the latest version of STIG supports the .extension directories with a trimmed down version of properties.json in it noting the name and optional namespace of the extended class. The method representation is unchanged.

**Comment by dalehenrich** [comment]
Great! Getting dang close!

What are your thoughts on Issue #2?
