### ISSUE TITLE
use README.md for class comments

### ISSUE THREAD

**Issue by dalehenrich** [CampSmalltalk/Cypress#5]
If we use README.md for the class comments, then users can include markup in the class comment for extra richness in the github environment ... markup isn't that bad to read straight up (especially since links can be pushed to the bottom of the post with _reference-style links_, [like this](http://daringfireball.net/projects/markdown/syntax#link)) and straight text is just straight text ...

**Comment by mkobetic** [comment]
Yup, I agree. That's why the there's STIG.CommentFile global that you can set to whatever you want. Should it default to 'README.md' ?

**Comment by dalehenrich** [comment]
Yeah, I think we might as well start off on the "right foot" ... with the .md extensions folks will be encourage to use markdown in their class comments ...
